# Get Data
We will using helper fuction under /src to get the data we need

## Import liberary

In [1]:
# Import the necessary libraries
import sys
import os
import pandas as pd
import warnings

# Add the src folder to the path
sys.path.append(os.path.abspath('..'))
warnings.filterwarnings("ignore", category=FutureWarning)

# Import the classes
from src.connect_wrds import get_wrds_data
from src.yahoo_finance import yahoo_finance
from src.ploygon import polygon
from src.financial_datasets import FinancialDatasets
from src.connect_db import ConnectDB

# Initialize the classes
yf = yahoo_finance()
pl = polygon()
fd = FinancialDatasets()

db =ConnectDB()
engine = db.get_engine()

FINANCIAL_DATASETS_API_KEY is set
YAHOO_CONSUMER_KEY and YAHOO_CONSUMER_SECRET are set
YAHOO_APP_ID is set
POLYGON_API_KEY is set
DB_USER and DB_PASSWORD are set

## WRDS

In [25]:
tickers = ['AAPL', 'MSFT', 'GOOGL', 'AMZN', 'NVDA', 'META', 'TSLA', 'NFLX', 'ADBE',
                'CRM', 'AMD', 'INTC', 'AVGO', 'QCOM', 'SHOP', 'ZM', 'SNOW', 'PYPL', 'PLTR']
start_date = '2024-01-01'
end_date = '2025-03-18'

In [26]:
WRDS_datasets = get_wrds_data(
    tickers=tickers, 
    start_date=start_date, 
    end_date=end_date
)

Loading library list...

2025-03-19 21:39:13,159 - src.connect_wrds - INFO - Successfully connected to WRDS
2025-03-19 21:39:13,199 - src.connect_wrds - INFO - Retrieved 19 GVKEYs for tickers
2025-03-19 21:39:13,290 - src.connect_wrds - INFO - Retrieved 492 financial ratio records
2025-03-19 21:39:13,331 - src.connect_wrds - INFO - Retrieved 23 annual fundamental records

Done

2025-03-19 21:39:13,391 - src.connect_wrds - INFO - Retrieved 82 quarterly fundamental records
2025-03-19 21:39:13,449 - src.connect_wrds - INFO - Retrieved 1000 security daily records
2025-03-19 21:39:13,450 - src.connect_wrds - INFO - Using 19 existing identifiers
2025-03-19 21:39:13,484 - src.connect_wrds - INFO - Retrieved 23 debt structure records
2025-03-19 21:39:13,522 - src.connect_wrds - INFO - Retrieved 23 equity structure records
2025-03-19 21:39:13,555 - src.connect_wrds - INFO - Retrieved 23 capital structure summary records
2025-03-19 21:39:13,782 - src.connect_wrds - INFO - Retrieved 4388 key development records
2025-03-19 21:39:13,785 - src.connect_wrds - INFO - Saved financial_ratios to data/compustat/financial_ratios.csv
2025-03-19 21:39:13,786 - src.connect_wrds - INFO - Saved fundamentals_annual to data/compustat/fundamentals_annual.csv
2025-03-19 21:39:13,788 - src.connect_wrds - INFO - Saved fundamentals_quarterly to data/compustat/fundamentals_quarterly.csv
2025-03-19 21:39:13,791 - src.connect_wrds - INFO - Saved security_daily to data/compustat/security_daily.csv
2025-03-19 21:39:13,791 - src.connect_wrds - INFO - Saved identifiers to data/compustat/identifiers.csv
2025-03-19 21:39:13,792 - src.connect_wrds - INFO - Saved capital_structure_debt to data/compustat/capital_structure_debt.csv
2025-03-19 21:39:13,793 - src.connect_wrds - INFO - Saved capital_structure_equity to data/compustat/capital_structure_equity.csv
2025-03-19 21:39:13,794 - src.connect_wrds - INFO - Saved capital_structure_summary to data/compustat/capital_structure_summary.csv
2025-03-19 21:39:13,828 - src.connect_wrds - INFO - Saved key_developments to data/compustat/key_developments.csv
2025-03-19 21:39:13,828 - src.connect_wrds - INFO - ------- Summary of Retrieved Datasets -------
2025-03-19 21:39:13,828 - src.connect_wrds - INFO - financial_ratios: SUCCESS - 492 records
2025-03-19 21:39:13,829 - src.connect_wrds - INFO - fundamentals_annual: SUCCESS - 23 records
2025-03-19 21:39:13,829 - src.connect_wrds - INFO - fundamentals_quarterly: SUCCESS - 82 records
2025-03-19 21:39:13,829 - src.connect_wrds - INFO - security_daily: SUCCESS - 1000 records
2025-03-19 21:39:13,829 - src.connect_wrds - INFO - identifiers: SUCCESS - 19 records
2025-03-19 21:39:13,829 - src.connect_wrds - INFO - capital_structure_debt: SUCCESS - 23 records
2025-03-19 21:39:13,829 - src.connect_wrds - INFO - capital_structure_equity: SUCCESS - 23 records
2025-03-19 21:39:13,829 - src.connect_wrds - INFO - capital_structure_summary: SUCCESS - 23 records
2025-03-19 21:39:13,830 - src.connect_wrds - INFO - key_developments: SUCCESS - 4388 records
2025-03-19 21:39:13,830 - src.connect_wrds - INFO - --------------------------------------------
2025-03-19 21:39:13,830 - src.connect_wrds - INFO - WRDS connection closed

In [27]:
for dataset in WRDS_datasets:
    print(dataset)

financial_ratios
fundamentals_annual
fundamentals_quarterly
security_daily
identifiers
capital_structure_debt
capital_structure_equity
capital_structure_summary
key_developments

In [28]:
WRDS_datasets['identifiers']

   ticker   gvkey                     conm
0    AAPL  001690                APPLE INC
1    ADBE  012540                ADOBE INC
2     AMD  001161   ADVANCED MICRO DEVICES
3    AMZN  064768           AMAZON.COM INC
4    AVGO  180711             BROADCOM INC
5     CRM  157855           SALESFORCE INC
6   GOOGL  160329             ALPHABET INC
7    INTC  006008               INTEL CORP
8    META  170617       META PLATFORMS INC
9    MSFT  012141           MICROSOFT CORP
10   NFLX  147579              NETFLIX INC
11   NVDA  117768              NVIDIA CORP
12   PLTR  036910   PALANTIR TECHNOLOG INC
13   PYPL  024616      PAYPAL HOLDINGS INC
14   QCOM  024800             QUALCOMM INC
15   SHOP  023650              SHOPIFY INC
16   SNOW  339965            SNOWFLAKE INC
17   TSLA  184996                TESLA INC
18     ZM  035005  ZOOM COMMUNICATIONS INC

In [13]:
WRDS_datasets['security_daily']

    ticker   datadate    prccm    prchm    prclm         cshom
0     MSFT 2025-03-31     <NA>     <NA>     <NA>          <NA>
1     QCOM 2025-03-31     <NA>     <NA>     <NA>          <NA>
2    GOOGL 2025-03-31     <NA>     <NA>     <NA>          <NA>
3     NVDA 2025-03-31     <NA>     <NA>     <NA>          <NA>
4     META 2025-03-31     <NA>     <NA>     <NA>          <NA>
..     ...        ...      ...      ...      ...           ...
995    CRM 2021-01-31   225.56    230.3  212.985   915445000.0
996   GOOG 2021-01-31  1835.74  1934.86   1699.0   329867000.0
997   SHOP 2021-01-31  1098.59  1247.45  1076.05   110044000.0
998   META 2021-01-31   258.33   286.79   244.61  2405448000.0
999    AMD 2021-01-31    85.64    99.23    85.02  1202712000.0

[1000 rows x 6 columns]

In [14]:
WRDS_datasets['financial_ratios']

,gvkey,datadate,fyear,at,lt,sale,ni,roe,roa,ticker,conm
0,035005,2025-01-31,2024,10988.421,2053.337,4665.433,1010.238,0.113064,0.091937,ZM,ZOOM COMMUNICATIONS INC
1,339965,2025-01-31,2024,9033.938,6027.295,3626.396,-1285.64,-0.428557,-0.142312,SNOW,SNOWFLAKE INC
2,157855,2025-01-31,2024,102928.0,41755.0,37895.0,6197.0,0.101303,0.060207,CRM,SALESFORCE INC
3,117768,2025-01-31,2024,111601.0,32274.0,130497.0,72880.0,0.918729,0.653041,NVDA,NVIDIA CORP
4,184996,2024-12-31,2024,122070.0,48390.0,97690.0,7091.0,0.097253,0.05809,TSLA,TESLA INC
...,...,...,...,...,...,...,...,...,...,...,...
487,001161,1974-03-31,1973,20.735,8.252,26.429,2.429,0.194585,0.117145,AMD,ADVANCED MICRO DEVICES
488,006008,1973-12-31,1973,50.567,22.679,65.593,9.214,0.330393,0.182214,INTC,INTEL CORP
489,001161,1973-03-31,1972,12.85,2.834,11.199,1.323,0.132089,0.102957,AMD,ADVANCED MICRO DEVICES
490,006008,1972-12-31,1972,21.944,4.548,22.971,3.084,0.177282,0.14054,INTC,INTEL CORP
491,006008,1971-12-31,1971,14.787,1.373,9.166,1.015,0.075667,0.068641,INTC,INTEL CORP

In [15]:
WRDS_datasets['fundamentals_annual']

,gvkey,datadate,fyear,fyr,indfmt,consol,at,lt,ceq,ch,...,cogs,xsga,ebit,ebitda,ni,ib,xrd,capx,ticker,conm
0,117768,2025-01-31,2024,1,INDL,C,111601.0,32274.0,79327.0,8589.0,...,30775.0,16405.0,81453.0,83317.0,72880.0,72880.0,12914.0,3236.0,NVDA,NVIDIA CORP
1,339965,2025-01-31,2024,1,INDL,C,9033.938,6027.295,2999.929,2628.798,...,1072.277,3808.168,-1436.557,-1254.049,-1285.64,-1285.64,1783.379,75.712,SNOW,SNOWFLAKE INC
2,157855,2025-01-31,2024,1,INDL,C,102928.0,41755.0,61173.0,8848.0,...,6893.0,20685.0,7666.0,10317.0,6197.0,6197.0,5493.0,658.0,CRM,SALESFORCE INC
3,035005,2025-01-31,2024,1,INDL,C,10988.421,2053.337,8935.084,1349.38,...,999.69,2671.948,871.163,993.795,1010.238,1010.238,852.415,136.56,ZM,ZOOM COMMUNICATIONS INC
4,064768,2024-12-31,2024,12,INDL,C,624894.0,338924.0,285970.0,78779.0,...,294221.0,242315.0,69438.0,101423.0,59248.0,59248.0,88544.0,82999.0,AMZN,AMAZON.COM INC
5,006008,2024-12-31,2024,12,INDL,C,196485.0,91453.0,99270.0,8249.0,...,24566.0,21864.0,-4708.0,6671.0,-18756.0,-18756.0,16546.0,23944.0,INTC,INTEL CORP
6,023650,2024-12-31,2024,12,INDL,C,13924.0,2366.0,11558.0,1498.0,...,4396.0,3428.0,1020.0,1056.0,2019.0,2019.0,1367.0,19.0,SHOP,SHOPIFY INC
7,024616,2024-12-31,2024,12,INDL,C,81611.0,61194.0,20417.0,6561.0,...,16433.0,8569.0,5763.0,6795.0,4147.0,4147.0,1500.0,683.0,PYPL,PAYPAL HOLDINGS INC
8,036910,2024-12-31,2024,12,INDL,C,6340.884,1246.477,5003.275,2098.524,...,534.403,1989.114,310.403,341.99,462.19,462.19,507.878,12.634,PLTR,PALANTIR TECHNOLOG INC
9,001161,2024-12-31,2024,12,INDL,C,69226.0,11658.0,57568.0,3787.0,...,11594.0,9053.0,2290.0,5138.0,1641.0,1641.0,6456.0,636.0,AMD,ADVANCED MICRO DEVICES
10,147579,2024-12-31,2024,12,INDL,C,53630.374,28886.807,24743.567,7804.733,...,20709.55,7544.888,10417.614,10746.528,8711.631,8711.631,2925.295,439.538,NFLX,NETFLIX INC
11,160329,2024-12-31,2024,12,INDL,C,450256.0,125172.0,321984.0,23466.0,...,130842.0,90759.0,113106.0,128417.0,100118.0,100118.0,49326.0,52535.0,GOOGL,ALPHABET INC
12,170617,2024-12-31,2024,12,INDL,C,276054.0,93417.0,182637.0,43889.0,...,14632.0,64752.0,69619.0,85117.0,62360.0,62360.0,43873.0,37256.0,META,META PLATFORMS INC
13,184996,2024-12-31,2024,12,INDL,C,122070.0,48390.0,72913.0,16139.0,...,74872.0,9690.0,7760.0,13128.0,7091.0,7091.0,4540.0,11342.0,TSLA,TESLA INC
14,012540,2024-11-30,2024,11,INDL,C,30230.0,16125.0,14105.0,7613.0,...,1996.0,11159.0,7775.0,8350.0,5560.0,5560.0,3944.0,183.0,ADBE,ADOBE INC
15,180711,2024-10-31,2024,10,INDL,C,165645.0,97967.0,67678.0,9348.0,...,12186.0,13729.0,15799.0,25659.0,5895.0,6168.0,9310.0,548.0,AVGO,BROADCOM INC
16,001690,2024-09-30,2024,9,INDL,C,364980.0,308030.0,56950.0,27343.0,...,202152.0,57467.0,123216.0,131416.0,93736.0,93736.0,31370.0,9447.0,AAPL,APPLE INC
17,024800,2024-09-30,2024,9,INDL,C,55154.0,28880.0,26274.0,7849.0,...,15354.0,11639.0,10263.0,11969.0,10142.0,10110.0,8893.0,1041.0,QCOM,QUALCOMM INC
18,012141,2024-06-30,2024,6,INDL,C,512163.0,243686.0,268477.0,18315.0,...,54114.0,61575.0,109433.0,129433.0,88136.0,88136.0,29510.0,44477.0,MSFT,MICROSOFT CORP
19,157855,2024-01-31,2023,1,INDL,C,99823.0,40177.0,59646.0,8472.0,...,6463.0,19426.0,5999.0,8968.0,4136.0,4136.0,4906.0,736.0,CRM,SALESFORCE INC
20,339965,2024-01-31,2023,1,INDL,C,8223.383,3032.789,5180.308,1762.749,...,823.063,2951.196,-1087.673,-967.77,-836.097,-836.097,1287.949,69.219,SNOW,SNOWFLAKE INC
21,117768,2024-01-31,2023,1,INDL,C,65728.0,22750.0,42978.0,7280.0,...,15113.0,11329.0,32972.0,34480.0,29760.0,29760.0,8675.0,1069.0,NVDA,NVIDIA CORP
22,035005,2024-01-31,2023,1,INDL,C,9929.793,1910.387,8019.406,1558.252,...,958.711,2765.386,698.676,803.127,637.462,637.462,803.187,126.953,ZM,ZOOM COMMUNICATIONS INC

In [16]:
WRDS_datasets['fundamentals_quarterly']

,gvkey,datadate,fyearq,fqtr,indfmt,consol,atq,ltq,ceqq,cheq,...,revtq,cogsq,xsgaq,oibdpq,niq,ibq,xrdq,capxy,ticker,conm
0,012540,2025-02-28,2025,1,INDL,C,29955.0,16860.0,13095.0,7435.0,...,5714.0,446.0,2888.0,2380.0,1811.0,1811.0,1026.0,26.0,ADBE,ADOBE INC
1,117768,2025-01-31,2024,4,INDL,C,111601.0,32274.0,79327.0,43210.0,...,39331.0,10065.0,4689.0,24577.0,22091.0,22091.0,3714.0,3236.0,NVDA,NVIDIA CORP
2,339965,2025-01-31,2024,4,INDL,C,9033.938,6027.295,2999.929,4637.671,...,986.77,295.205,1026.201,-334.636,-327.474,-327.474,492.49,75.712,SNOW,SNOWFLAKE INC
3,035005,2025-01-31,2024,4,INDL,C,10988.421,2053.337,8935.084,7791.709,...,1184.138,250.932,663.636,269.57,367.865,367.865,217.121,136.56,ZM,ZOOM COMMUNICATIONS INC
4,180711,2025-01-31,2025,1,INDL,C,165358.0,95569.0,69789.0,9307.0,...,14916.0,3131.0,3095.0,8690.0,5503.0,5503.0,2253.0,100.0,AVGO,BROADCOM INC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,339965,2024-01-31,2023,4,INDL,C,8223.383,3032.789,5180.308,3846.248,...,774.699,218.751,796.467,-240.519,-169.352,-169.352,364.476,69.219,SNOW,SNOWFLAKE INC
78,035005,2024-01-31,2023,4,INDL,C,9929.793,1910.387,8019.406,6969.359,...,1146.457,247.2,690.99,208.267,298.832,298.832,205.282,126.953,ZM,ZOOM COMMUNICATIONS INC
79,157855,2024-01-31,2023,4,INDL,C,99823.0,40177.0,59646.0,14194.0,...,9287.0,1418.0,5121.0,2748.0,1446.0,1446.0,1275.0,736.0,CRM,SALESFORCE INC
80,117768,2024-01-31,2023,4,INDL,C,65728.0,22750.0,42978.0,25984.0,...,22103.0,4925.0,3177.0,14001.0,12285.0,12285.0,2465.0,1069.0,NVDA,NVIDIA CORP
81,180711,2024-01-31,2024,1,INDL,C,177870.0,107586.0,70284.0,11864.0,...,11961.0,2969.0,3594.0,5398.0,1325.0,1274.0,2308.0,122.0,AVGO,BROADCOM INC

In [17]:
WRDS_datasets['capital_structure_debt']

,gvkey,datadate,fyear,dltt,dlc,dd1,dd2,dd3,dd4,dd5,ticker,conm
0,117768,2025-01-31,2024,9982.0,288.0,288.0,1000.0,0.0,1250.0,0.0,NVDA,NVIDIA CORP
1,339965,2025-01-31,2024,2649.347,35.923,35.923,<NA>,<NA>,<NA>,<NA>,SNOW,SNOWFLAKE INC
2,157855,2025-01-31,2024,11154.0,916.0,916.0,244.0,71.0,2529.0,12.0,CRM,SALESFORCE INC
3,035005,2025-01-31,2024,37.406,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,ZM,ZOOM COMMUNICATIONS INC
4,064768,2024-12-31,2024,138000.0,17401.0,17250.0,4760.0,10590.0,3895.0,4562.0,AMZN,AMAZON.COM INC
5,006008,2024-12-31,2024,46561.0,3910.0,3910.0,2606.0,3842.0,3179.0,3288.0,INTC,INTEL CORP
6,023650,2024-12-31,2024,190.0,936.0,936.0,0.0,0.0,0.0,0.0,SHOP,SHOPIFY INC
7,024616,2024-12-31,2024,10526.0,1331.0,1331.0,1403.0,506.0,242.0,1500.0,PYPL,PAYPAL HOLDINGS INC
8,036910,2024-12-31,2024,195.226,43.993,43.993,0.0,0.0,0.0,0.0,PLTR,PALANTIR TECHNOLOG INC
9,001161,2024-12-31,2024,2212.0,109.0,109.0,0.0,0.0,0.0,0.0,AMD,ADVANCED MICRO DEVICES
10,147579,2024-12-31,2024,15782.039,2212.935,2212.935,1000.0,1346.0,3500.0,4081.0,NFLX,NETFLIX INC
11,160329,2024-12-31,2024,24016.0,4121.0,4121.0,2208.0,1208.0,197.0,166.0,GOOGL,ALPHABET INC
12,170617,2024-12-31,2024,47751.0,2018.0,2018.0,68.0,2818.0,1568.0,1064.0,META,META PLATFORMS INC
13,184996,2024-12-31,2024,10360.0,3263.0,3263.0,4116.0,699.0,243.0,95.0,TSLA,TESLA INC
14,012540,2024-11-30,2024,4482.0,1574.0,1574.0,0.0,1350.0,0.0,750.0,ADBE,ADOBE INC
15,180711,2024-10-31,2024,67438.0,1478.0,1478.0,3160.0,11735.0,4272.0,12657.0,AVGO,BROADCOM INC
16,001690,2024-09-30,2024,96548.0,22511.0,12544.0,12473.0,9995.0,7838.0,5189.0,AAPL,APPLE INC
17,024800,2024-09-30,2024,13978.0,1462.0,1462.0,0.0,2000.0,1000.0,0.0,QCOM,QUALCOMM INC
18,012141,2024-06-30,2024,82981.0,14871.0,8178.0,6021.0,12287.0,3026.0,4514.0,MSFT,MICROSOFT CORP
19,157855,2024-01-31,2023,11673.0,1889.0,1889.0,342.0,230.0,52.0,2507.0,CRM,SALESFORCE INC
20,339965,2024-01-31,2023,254.037,33.944,33.944,0.0,0.0,0.0,0.0,SNOW,SNOWFLAKE INC
21,117768,2024-01-31,2023,9578.0,1478.0,1478.0,0.0,1000.0,0.0,1250.0,NVDA,NVIDIA CORP
22,035005,2024-01-31,2023,48.308,24.645,24.645,0.0,0.0,0.0,0.0,ZM,ZOOM COMMUNICATIONS INC

In [18]:
WRDS_datasets['capital_structure_equity']

,gvkey,datadate,fyear,ceq,seq,pstk,csho,prcc_f,dvc,ticker,conm
0,117768,2025-01-31,2024,79327.0,79327.0,0.0,24477.0,120.07,834.0,NVDA,NVIDIA CORP
1,339965,2025-01-31,2024,2999.929,2999.929,0.0,330.071,181.51,<NA>,SNOW,SNOWFLAKE INC
2,157855,2025-01-31,2024,61173.0,61173.0,0.0,962.0,341.7,1549.0,CRM,SALESFORCE INC
3,035005,2025-01-31,2024,8935.084,8935.084,0.0,306.624,86.94,<NA>,ZM,ZOOM COMMUNICATIONS INC
4,064768,2024-12-31,2024,285970.0,285970.0,0.0,10593.0,219.39,0.0,AMZN,AMAZON.COM INC
5,006008,2024-12-31,2024,99270.0,99270.0,0.0,4330.0,20.05,1599.0,INTC,INTEL CORP
6,023650,2024-12-31,2024,11558.0,11558.0,0.0,1294.58,106.33,0.0,SHOP,SHOPIFY INC
7,024616,2024-12-31,2024,20417.0,20417.0,0.0,993.0,85.35,0.0,PYPL,PAYPAL HOLDINGS INC
8,036910,2024-12-31,2024,5003.275,5003.275,0.0,2338.795,75.63,0.0,PLTR,PALANTIR TECHNOLOG INC
9,001161,2024-12-31,2024,57568.0,57568.0,0.0,1622.0,120.79,0.0,AMD,ADVANCED MICRO DEVICES
10,147579,2024-12-31,2024,24743.567,24743.567,0.0,427.757,891.32,0.0,NFLX,NETFLIX INC
11,160329,2024-12-31,2024,321984.0,321984.0,0.0,12211.0,189.3,7577.0,GOOGL,ALPHABET INC
12,170617,2024-12-31,2024,182637.0,182637.0,0.0,2534.0,585.51,5121.0,META,META PLATFORMS INC
13,184996,2024-12-31,2024,72913.0,72913.0,0.0,3216.0,403.84,0.0,TSLA,TESLA INC
14,012540,2024-11-30,2024,14105.0,14105.0,0.0,441.0,515.93,0.0,ADBE,ADOBE INC
15,180711,2024-10-31,2024,67678.0,67678.0,0.0,4686.0,169.77,9814.0,AVGO,BROADCOM INC
16,001690,2024-09-30,2024,56950.0,56950.0,0.0,15116.786,233.0,15218.0,AAPL,APPLE INC
17,024800,2024-09-30,2024,26274.0,26274.0,0.0,1113.0,170.05,3794.0,QCOM,QUALCOMM INC
18,012141,2024-06-30,2024,268477.0,268477.0,0.0,7434.0,446.95,22293.0,MSFT,MICROSOFT CORP
19,157855,2024-01-31,2023,59646.0,59646.0,0.0,971.0,281.09,0.0,CRM,SALESFORCE INC
20,339965,2024-01-31,2023,5180.308,5180.308,0.0,333.961,195.64,0.0,SNOW,SNOWFLAKE INC
21,117768,2024-01-31,2023,42978.0,42978.0,0.0,2464.0,615.27,395.0,NVDA,NVIDIA CORP
22,035005,2024-01-31,2023,8019.406,8019.406,0.0,307.558,64.61,0.0,ZM,ZOOM COMMUNICATIONS INC

In [19]:
WRDS_datasets['capital_structure_summary']

,gvkey,datadate,fyear,at,lt,dltt,dlc,ceq,seq,csho,prcc_f,mkvalt,ticker,conm,debt_to_equity,debt_to_assets
0,117768,2025-01-31,2024,111601.0,32274.0,9982.0,288.0,79327.0,79327.0,24477.0,120.07,2938953.39,NVDA,NVIDIA CORP,0.129464,0.092024
1,339965,2025-01-31,2024,9033.938,6027.295,2649.347,35.923,2999.929,2999.929,330.071,181.51,59911.1872,SNOW,SNOWFLAKE INC,0.895111,0.297242
2,157855,2025-01-31,2024,102928.0,41755.0,11154.0,916.0,61173.0,61173.0,962.0,341.7,328715.4,CRM,SALESFORCE INC,0.197309,0.117266
3,035005,2025-01-31,2024,10988.421,2053.337,37.406,<NA>,8935.084,8935.084,306.624,86.94,26657.8906,ZM,ZOOM COMMUNICATIONS INC,0.004186,0.003404
4,064768,2024-12-31,2024,624894.0,338924.0,138000.0,17401.0,285970.0,285970.0,10593.0,219.39,2323998.27,AMZN,AMAZON.COM INC,0.543417,0.248684
5,006008,2024-12-31,2024,196485.0,91453.0,46561.0,3910.0,99270.0,99270.0,4330.0,20.05,86816.5,INTC,INTEL CORP,0.508421,0.256869
6,023650,2024-12-31,2024,13924.0,2366.0,190.0,936.0,11558.0,11558.0,1294.58,106.33,137652.6914,SHOP,SHOPIFY INC,0.097422,0.080868
7,024616,2024-12-31,2024,81611.0,61194.0,10526.0,1331.0,20417.0,20417.0,993.0,85.35,84752.55,PYPL,PAYPAL HOLDINGS INC,0.580742,0.145287
8,036910,2024-12-31,2024,6340.884,1246.477,195.226,43.993,5003.275,5003.275,2338.795,75.63,176883.0659,PLTR,PALANTIR TECHNOLOG INC,0.047812,0.037726
9,001161,2024-12-31,2024,69226.0,11658.0,2212.0,109.0,57568.0,57568.0,1622.0,120.79,195921.38,AMD,ADVANCED MICRO DEVICES,0.040318,0.033528
10,147579,2024-12-31,2024,53630.374,28886.807,15782.039,2212.935,24743.567,24743.567,427.757,891.32,381268.3692,NFLX,NETFLIX INC,0.727259,0.335537
11,160329,2024-12-31,2024,450256.0,125172.0,24016.0,4121.0,321984.0,321984.0,12211.0,189.3,2317829.4,GOOGL,ALPHABET INC,0.087386,0.062491
12,170617,2024-12-31,2024,276054.0,93417.0,47751.0,2018.0,182637.0,182637.0,2534.0,585.51,1483682.34,META,META PLATFORMS INC,0.272502,0.180287
13,184996,2024-12-31,2024,122070.0,48390.0,10360.0,3263.0,72913.0,72913.0,3216.0,403.84,1298749.44,TSLA,TESLA INC,0.186839,0.1116
14,012540,2024-11-30,2024,30230.0,16125.0,4482.0,1574.0,14105.0,14105.0,441.0,515.93,227525.13,ADBE,ADOBE INC,0.429351,0.200331
15,180711,2024-10-31,2024,165645.0,97967.0,67438.0,1478.0,67678.0,67678.0,4686.0,169.77,795542.22,AVGO,BROADCOM INC,1.018293,0.416046
16,001690,2024-09-30,2024,364980.0,308030.0,96548.0,22511.0,56950.0,56950.0,15116.786,233.0,3522211.138,AAPL,APPLE INC,2.090588,0.326207
17,024800,2024-09-30,2024,55154.0,28880.0,13978.0,1462.0,26274.0,26274.0,1113.0,170.05,189265.65,QCOM,QUALCOMM INC,0.587653,0.279943
18,012141,2024-06-30,2024,512163.0,243686.0,82981.0,14871.0,268477.0,268477.0,7434.0,446.95,3322626.3,MSFT,MICROSOFT CORP,0.364471,0.191056
19,157855,2024-01-31,2023,99823.0,40177.0,11673.0,1889.0,59646.0,59646.0,971.0,281.09,272938.39,CRM,SALESFORCE INC,0.227375,0.13586
20,339965,2024-01-31,2023,8223.383,3032.789,254.037,33.944,5180.308,5180.308,333.961,195.64,65336.13,SNOW,SNOWFLAKE INC,0.055591,0.03502
21,117768,2024-01-31,2023,65728.0,22750.0,9578.0,1478.0,42978.0,42978.0,2464.0,615.27,1516025.28,NVDA,NVIDIA CORP,0.257248,0.168208
22,035005,2024-01-31,2023,9929.793,1910.387,48.308,24.645,8019.406,8019.406,307.558,64.61,19871.3224,ZM,ZOOM COMMUNICATIONS INC,0.009097,0.007347

In [20]:
WRDS_datasets['key_developments']

,keydevid,companyid,companyname,headline,keydeveventtypeid,eventtype,keydevtoobjectroletypeid,objectroletype,announcedate,announcetime,...,entereddateutc,lastmodifieddate,lastmodifieddateutc,mostimportantdateutc,speffectivedate,sptodate,gvkey,sourcetypename,ticker,conm
0,1934211098.0,20765463.0,"Meta Platforms, Inc.","Meta Platforms, Inc. Presents at 2025 SXSW Con...",51,Company Conference Presentations,1,Target,2025-03-07,16:41:00,...,2025-03-08 03:00:00,2025-03-07 22:03:00,2025-03-08 03:03:00,2025-03-07 00:00:00,2025-03-08 03:15:14,NaT,170617,MULTIPLE,META,META PLATFORMS INC
1,1934042331.0,25016048.0,Broadcom Inc.,Broadcom Inc. Provides Earnings Guidance for t...,29,Corporate Guidance - New/Confirmed,1,Target,2025-03-06,21:15:00,...,2025-03-07 03:53:00,2025-03-06 22:55:00,2025-03-07 03:55:00,2025-03-06 21:15:00,2025-03-07 04:00:23,NaT,180711,PR Newswire,AVGO,BROADCOM INC
2,1934012039.0,25016048.0,Broadcom Inc.,Broadcom Inc. Reports Earnings Results for the...,28,Announcements of Earnings,1,Target,2025-03-06,21:15:00,...,2025-03-06 23:16:00,2025-03-06 19:03:00,2025-03-07 00:03:00,2025-03-06 21:15:00,2025-03-07 00:15:10,NaT,180711,S&P Capital IQ Financials Database,AVGO,BROADCOM INC
3,1934012039.0,25016048.0,Broadcom Inc.,Broadcom Inc. Reports Earnings Results for the...,28,Announcements of Earnings,1,Target,2025-03-06,21:15:00,...,2025-03-06 23:16:00,2025-03-06 18:19:00,2025-03-06 23:19:00,2025-03-06 21:15:00,2025-03-06 23:30:14,2025-03-07 00:15:09,180711,S&P Capital IQ Financials Database,AVGO,BROADCOM INC
4,1934000534.0,21835.0,Microsoft Corporation,The TCW Group Collaborates with Microsoft for ...,23,Client Announcements,1,Target,2025-03-06,15:00:00,...,2025-03-06 18:07:00,2025-03-06 13:09:00,2025-03-06 18:09:00,2025-03-06 15:00:00,2025-03-06 18:15:12,NaT,012141,Business Wire,MSFT,MICROSOFT CORP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4383,1866975921.0,32307.0,NVIDIA Corporation,NVIDIA Corporation - Special Call,194,Special Calls,1,Target,2024-01-02,00:00:00,...,2024-01-03 05:08:00,2024-01-03 00:09:00,2024-01-03 05:09:00,2024-01-23 16:00:00,2024-01-23 00:00:00,NaT,117768,Company Website,NVDA,NVIDIA CORP
4384,1866977469.0,32307.0,NVIDIA Corporation,NVIDIA Corporation - Special Call,194,Special Calls,1,Target,2024-01-02,00:00:00,...,2024-01-03 05:23:00,2024-01-08 11:03:00,2024-01-08 16:03:00,2024-01-17 09:00:00,2024-01-17 00:00:00,NaT,117768,Company Website,NVDA,NVIDIA CORP
4385,1866628761.0,21127.0,Intel Corporation,Intel Corporation Presents at Optical Fiber Co...,51,Company Conference Presentations,1,Target,2024-01-02,09:28:00,...,2024-01-02 16:00:00,2024-01-03 12:03:00,2024-01-03 17:03:00,2024-03-26 00:00:00,2024-03-26 00:00:00,NaT,006008,Company Website,INTC,INTEL CORP
4386,1917814107.0,21835.0,Microsoft Corporation,Microsoft Corporation Presents at Road to TMRE...,51,Company Conference Presentations,1,Target,2024-01-01,00:00:00,...,2025-01-23 02:00:00,2025-01-22 21:03:00,2025-01-23 02:03:00,2024-07-30 00:00:00,2025-01-23 02:15:08,NaT,012141,Company Website,MSFT,MICROSOFT CORP
4387,1870632623.0,20765463.0,"Meta Platforms, Inc.","Meta Platforms, Inc. announces an Increase in ...",230,Buyback - Change in Plan Terms,1,Target,2024-01-01,00:00:00,...,2024-02-02 05:50:00,2024-04-27 14:33:00,2024-04-27 18:33:00,2024-01-01 00:00:00,2024-04-27 18:45:15,NaT,170617,Capital IQ Buybacks Database,META,META PLATFORMS INC

## Yahoo Fiance

In [2]:
tickers = ['AAPL', 'MSFT', 'GOOG', 'AMZN', 'TSLA', 'META', 'NFLX', 'NVDA', 'AMD', 'NVDA', 
           'TSLA', 'BA', 'V', 'GOOG', 'SPY', 'SPCE', 'TWTR', 'BABA', 'MSTR', 'DIS', 
           'PYPL', 'SHOP', 'COIN', 'SQ', 'INTC', 'CSCO', 'IBM', 'GE', 'AMD', 'WMT', 'T']

In [3]:
data = yf.get_data(tickers, '2024-03-18', '2025-03-18')

In [4]:
df = pd.DataFrame(data)
df

                         open        high         low       close     volume  \
symbol date
AAPL   2024-03-18  175.570007  177.710007  173.520004  173.720001   75604200
       2024-03-19  174.339996  176.610001  173.029999  176.080002   55215200
       2024-03-20  175.720001  178.669998  175.089996  178.669998   53423100
       2024-03-21  177.050003  177.490005  170.839996  171.369995  106181300
       2024-03-22  171.759995  173.050003  170.059998  172.279999   71106600
...                       ...         ...         ...         ...        ...
T      2025-03-11   26.469999   26.830000   25.590000   26.010000   74574300
       2025-03-12   25.629999   25.860001   24.889999   25.719999   62383200
       2025-03-13   25.790001   26.459999   25.760000   26.090000   37698500
       2025-03-14   25.799999   26.650000   25.750000   26.580000   37591300
       2025-03-17   26.570000   26.930000   26.250000   26.830000   45570000

                     adjclose  dividends  splits
symbol date
AAPL   2024-03-18  172.903580        0.0     0.0
       2024-03-19  175.252487        0.0     0.0
       2024-03-20  177.830307        0.0     0.0
       2024-03-21  170.564621        0.0     0.0
       2024-03-22  171.470352        0.0     0.0
...                       ...        ...     ...
T      2025-03-11   26.010000        0.0     0.0
       2025-03-12   25.719999        0.0     0.0
       2025-03-13   26.090000        0.0     0.0
       2025-03-14   26.580000        0.0     0.0
       2025-03-17   26.830000        0.0     0.0

[6500 rows x 8 columns]

In [5]:
valuation_metrics = yf.get_valuation_metrics(tickers)
valuation_metrics

Error fetching data for FB: Quote not found for ticker symbol: FB
Error fetching data for TWTR: Quote not found for ticker symbol: TWTR

   Ticker Price/Book EV/EBITDA
0    AAPL  48.688595    23.575
1    MSFT   9.548044    20.293
2    GOOG   6.297611    14.791
3    AMZN   7.224852    17.413
4    TSLA   10.54296     53.93
5    META    8.16247     17.29
6    NFLX   16.69038      37.8
7    NVDA  36.908363    33.409
8     AMD   3.017159    32.024
9    NVDA  36.908363    33.409
10   TSLA   10.54296     53.93
11     BA        N/A   -18.439
12      V  17.812403    25.846
13   GOOG   6.297611    14.791
14    SPY        N/A       N/A
15   SPCE    0.44333    -0.179
16   BABA   0.331034    13.377
17   MSTR   4.139916   -43.356
18    DIS    1.79253    12.154
19   PYPL   3.415204    11.218
20   SHOP  11.495295    91.456
21   COIN   4.732952    19.443
22     SQ   2.690677     42.31
23   INTC   1.061677    19.484
24   CSCO   5.370397    17.456
25    IBM   8.588874    26.133
26     GE  11.452759    24.819
27    AMD   3.017159    32.024
28    WMT   7.639513    17.625
29      T   1.846621     7.949

## Polygon

In [6]:
data = pl.get_data('AAPL', multiplier=1, timespan='minute', from_date='2025-03-13', to_date='2025-03-17', limit=100000)
data

,ticker,open,high,low,close,volume,vwap,timestamp,transactions,otc
0,AAPL,216.0000,216.00,215.7000,215.70,3945.0,215.8287,2025-03-13 08:00:00,150,None
1,AAPL,215.6000,215.60,215.2500,215.40,3347.0,215.3760,2025-03-13 08:01:00,131,None
2,AAPL,215.6000,215.60,215.4000,215.40,1934.0,215.4996,2025-03-13 08:03:00,132,None
3,AAPL,215.4500,215.46,215.4500,215.46,1203.0,215.4716,2025-03-13 08:04:00,103,None
4,AAPL,215.4500,215.50,215.4500,215.50,1392.0,215.4825,2025-03-13 08:05:00,31,None
...,...,...,...,...,...,...,...,...,...,...
2320,AAPL,213.8800,213.93,213.8800,213.93,687.0,213.8892,2025-03-17 23:55:00,6,None
2321,AAPL,213.8812,213.93,213.8812,213.90,802.0,213.8999,2025-03-17 23:56:00,10,None
2322,AAPL,213.9300,213.93,213.9300,213.93,414.0,213.9299,2025-03-17 23:57:00,9,None
2323,AAPL,213.9200,213.92,213.8800,213.88,809.0,213.9067,2025-03-17 23:58:00,17,None
2324,AAPL,213.9225,213.93,213.8092,213.93,643.0,213.9001,2025-03-17 23:59:00,17,None

In [7]:
tickers = ['AAPL', 'TSLA', 'META', 'NVDA']
data = pl.get_data_multiple(tickers, multiplier=1, timespan='minute', from_date='2025-03-13', to_date='2025-03-17', limit=100000)
data

,ticker,open,high,low,close,volume,vwap,timestamp,transactions,otc
0,AAPL,216.0000,216.00,215.7000,215.7000,3945.0,215.8287,2025-03-13 08:00:00,150,None
1,AAPL,215.6000,215.60,215.2500,215.4000,3347.0,215.3760,2025-03-13 08:01:00,131,None
2,AAPL,215.6000,215.60,215.4000,215.4000,1934.0,215.4996,2025-03-13 08:03:00,132,None
3,AAPL,215.4500,215.46,215.4500,215.4600,1203.0,215.4716,2025-03-13 08:04:00,103,None
4,AAPL,215.4500,215.50,215.4500,215.5000,1392.0,215.4825,2025-03-13 08:05:00,31,None
...,...,...,...,...,...,...,...,...,...,...
9973,NVDA,119.5000,119.50,119.4700,119.4700,9336.0,119.4875,2025-03-17 23:55:00,107,None
9974,NVDA,119.4700,119.50,119.4700,119.5000,18260.0,119.4765,2025-03-17 23:56:00,143,None
9975,NVDA,119.5000,119.54,119.4700,119.5392,12991.0,119.4959,2025-03-17 23:57:00,116,None
9976,NVDA,119.5300,119.55,119.5001,119.5305,15010.0,119.5271,2025-03-17 23:58:00,109,None
9977,NVDA,119.5399,119.54,119.5100,119.5101,31535.0,119.5201,2025-03-17 23:59:00,206,None

In [8]:
ticker = 'AAPL'
from_date = '2025-03-16'
to_date = '2025-03-18'
news, news_df = pl.get_news(ticker, from_date, to_date, strict=True)

In [9]:
news_df

,id,title,publisher_name,author,description,article_url,published_utc,tickers,keywords,sentiment,sentiment_reasoning,insight_tickers,published_est
2,7213f31ed41ddf47a9a141911caf29c59b5357c6974d25...,NASDAQ Correction: 2 AI Stocks That Aren't Wor...,The Motley Fool,Keithen Drury,"The article discusses two stocks, Apple and Pa...",https://www.fool.com/investing/2025/03/16/nasd...,2025-03-16 11:30:00+00:00,"[AAPL, PLTR]","[Apple, Palantir Technologies, market sell-off...",negative,The author believes Apple's growth is projecte...,AAPL,2025-03-16 07:30:00-04:00
4,1e79ff8650a1f51b1b22faaf285b31d08a343f5ac71e9c...,Consumer Tech News (Mar 10-Mar 14): Manus AI C...,Benzinga,Lekha Gupta,The article discusses various developments in ...,https://www.benzinga.com/news/large-cap/25/03/...,2025-03-16 15:38:04+00:00,"[AAPL, AMZN, BABA, BLNK, GOOG, GOOGL, META, MS...","[consumer tech, automotive industry, Tesla, Ma...",positive,The article mentions that Apple is preparing f...,AAPL,2025-03-16 11:38:04-04:00
5,5b5b66d9d6554bc4d0034709a7a8e1fa2807c802577b7c...,Warren Buffett's Warning to Wall Street Just G...,The Motley Fool,The Motley Fool,"Warren Buffett's recent actions, such as reduc...",https://www.fool.com/investing/2025/03/16/buff...,2025-03-16 22:10:00+00:00,"[AAPL, BAC, BACpB, BACpE, BACpK, BACpL, BACpM,...","[Warren Buffett, S&P 500, Nasdaq, tariffs, val...",neutral,"Buffett reduced his holdings in Apple, which c...",AAPL,2025-03-16 18:10:00-04:00
6,0c9d43bad1a9b97d9be295884ad764b01c159813069e00...,"Can This Unstoppable Stock Join Apple, Microso...",The Motley Fool,The Motley Fool,The article discusses the potential for Netfli...,https://www.fool.com/investing/2025/03/16/unst...,2025-03-16 22:30:00+00:00,"[AAPL, MSFT, NVDA, AMZN, GOOG, GOOGL, META, NFLX]","[Netflix, trillion-dollar companies, streaming...",positive,Apple is mentioned as one of the existing tril...,AAPL,2025-03-16 18:30:00-04:00
7,f694bfdee3560ea56222e568cadb6455b3b4738a7b87fc...,Apple Just Gave Taiwan Semiconductor Investors...,The Motley Fool,Adam Spatacco,Apple announced a $500 billion investment in A...,https://www.fool.com/investing/2025/03/17/appl...,2025-03-17 16:15:00+00:00,[AAPL],"[Apple, Taiwan Semiconductor Manufacturing Com...",positive,Apple's $500 billion investment in AI infrastr...,AAPL,2025-03-17 12:15:00-04:00
8,adf5edb350325db5d6b07e812fbaafcdd21a98581cb0f6...,Apple Stock: Optimism Rides High Despite 2025 ...,Investing.com,The Tokenist,Apple's stock has been on a downward trajector...,https://www.investing.com/analysis/apple-stock...,2025-03-17 19:52:00+00:00,"[AAPL, BABA]","[Apple, AI, Siri, Alibaba, stock market]",positive,Analysts remain optimistic about Apple's long-...,AAPL,2025-03-17 15:52:00-04:00
10,7de918d265452b5b4b0847184ad45ab1556a566a0f307c...,Online Gaming Market Forecast Report and Compa...,GlobeNewswire Inc.,Researchandmarkets.Com,The online gaming market is expected to grow s...,https://www.globenewswire.com/news-release/202...,2025-03-18 11:00:00+00:00,"[AAPL, CCOEY, EA, MSFT, NTDOY, SONY, TCEHY]","[online gaming, market forecast, company analy...",neutral,The article does not provide any specific info...,AAPL,2025-03-18 07:00:00-04:00
12,bebd182508b1ca718efbc830df3abf0500f683864d4cfb...,"Equity Exposure Plummets, Cash Holdings Jump A...",Benzinga,Piero Cingari,"Investor confidence is declining, with cash le...",https://www.benzinga.com/economics/macro-econo...,2025-03-18 15:13:27+00:00,"[AAPL, AMZN, SPY]","[equity exposure, cash holdings, US exceptiona...",negative,The article mentions a sharp rotation out of U...,AAPL,2025-03-18 11:13:27-04:00
13,011bc7413345c1ef9f2d03f72dc8c12430ab9e17520cc6...,Purpose Investments Inc. annonce les distribut...,GlobeNewswire Inc.,N/A,Purpose Investments announced the March 2025 d...,https://www.globenewswire.com/news-release/202...,2025-03-18 23:15:00+00:00,"[AAPL, MSFT, AMD, AMZN, GOOG, GOOGL, META, NVD...","[Purpose Investments, ETFs, Closed-End Funds, ...",positive,The article mentions a monthly distribution fo...,AAPL,2025-03-18 19:15:00-04:00

## Financial Datasets

In [10]:
ticker = 'AAPL'
facts = fd.get_company_facts(ticker)
facts

{'company_facts': {'ticker': 'AAPL',
  'name': 'Apple Inc',
  'cik': '0000320193',
  'industry': 'Consumer Electronics',
  'sector': 'Technology',
  'category': 'Common Stock',
  'exchange': 'NASDAQ',
  'is_active': True,
  'listing_date': '1980-12-12',
  'location': 'California; U.S.A',
  'market_cap': 3195044706370.0,
  'number_of_employees': 164000,
  'sec_filings_url': 'https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0000320193',
  'sic_code': '3571.0',
  'sic_industry': 'Electronic Computers',
  'sic_sector': 'Manufacturing',
  'website_url': 'https://www.apple.com',
  'weighted_average_shares': 15022073000}}

In [11]:
ticker = 'AAPL'
press_releases = fd.get_press_releases(ticker)
press_releases

AAPL is not available
['ABL', 'ABM', 'ABR', 'ABSI', 'ACHV', 'ACMR', 'ACU', 'ADT', 'ADV', 'AFCG', 'AGI', 'AGIO', 'AHH', 'AIP', 'AIRS', 'ALCO', 'ALEC', 'ALGS', 'ALLO', 'ALT', 'ALTG', 'ALTO', 'ALXO', 'AMPY', 'AMRN', 'ANIK', 'ANIP', 'APGE', 'API', 'APLS', 'APYX', 'AQST', 'ARHS', 'ARKO', 'AROC', 'ARQ', 'ARQT', 'ARR', 'ASNS', 'ASPS', 'ASRT', 'ASTL', 'ASUR', 'ATNI', 'ATYR', 'AUTL', 'AVAH', 'AVDL', 'AVIR', 'AVO', 'AVPT', 'AWRE', 'AXGN', 'AYI', 'BBCP', 'BBIO', 'BBNX', 'BBSI', 'BBWI', 'BDSX', 'BEKE', 'BENF', 'BGFV', 'BIGC', 'BIRD', 'BKR', 'BLDE', 'BLTE', 'BNGO', 'BOOM', 'BRFH', 'BRLT', 'BRY', 'BTTR', 'BURL', 'BVS', 'BWAY', 'BWEN', 'BYND', 'BZ', 'CAPR', 'CARG', 'CBLL', 'CBUS', 'CCAP', 'CCI', 'CCIF', 'CDXS', 'CECO', 'CGBD', 'CHDN', 'CHRS', 'CISS', 'CLAR', 'CLLS', 'CLMB', 'CLOV', 'CMLS', 'CMPO', 'CNXC', 'CODI', 'COHN', 'COLD', 'COLL', 'COO', 'CPRX', 'CPSS', 'CRDF', 'CREX', 'CRON', 'CRVS', 'CTKB', 'CTMX', 'CTSO', 'CVE', 'CVGI', 'CVGW', 'CWCO', 'CWEN', 'CWST', 'CYTK', 'DAKT', 'DALN', 'DAVE', 'DCO', 'DFLI', 'DH', 'DLNG', 'DLTH', 'DSX', 'DTC', 'DTE', 'DTM', 'DXLG', 'DY', 'ECO', 'ECOR', 'ECX', 'EDRY', 'EGO', 'EH', 'EIG', 'EKSO', 'ELUT', 'EOSE', 'EPAC', 'ERE-UN', 'ESEA', 'ESPR', 'EVCM', 'EVOK', 'EWCZ', 'EXK', 'EXOD', 'EXPI', 'EYPT', 'FA', 'FARO', 'FCEL', 'FCN', 'FDS', 'FDUS', 'FEIM', 'FENC', 'FGEN', 'FIVE', 'FLL', 'FLNT', 'FLUT', 'FLX', 'FLYW', 'FMCC', 'FMX', 'FOLD', 'FOSL', 'FOXF', 'FRPH', 'FRPT', 'FSM', 'FSTR', 'FTEK', 'FTG', 'FTS', 'FUFU', 'FULC', 'FUTU', 'FWRG', 'GASS', 'GAUZ', 'GCT', 'GETY', 'GEVO', 'GHI', 'GIFI', 'GIII', 'GIL', 'GLBE', 'GLPI', 'GLRE', 'GME', 'GOCO', 'GOGO', 'GSHD', 'GSL', 'GTE', 'GUTS', 'GWRS', 'HBIO', 'HCI', 'HCM', 'HDL', 'HDSN', 'HFFG', 'HIMX', 'HLMN', 'HOOD', 'HOV', 'HPK', 'HPQ', 'HQY', 'HSON', 'HST', 'HTHT', 'HUIZ', 'HUT', 'HYFM', 'HYPR', 'ICAD', 'ICCC', 'ICG', 'ICUI', 'IMCR', 'IMPP', 'INKT', 'INSE', 'INSG', 'IOVA', 'IRIX', 'IRMD', 'ITGR', 'ITRI', 'JD', 'JG', 'JYNT', 'KC', 'KIDS', 'KMDA', 'KNSA', 'KPLT', 'KRKR', 'KRT', 'KSPI', 'KTOS', 'KULR', 'KURA', 'KVHI', 'KYMR', 'LAMR', 'LAR', 'LCUT', 'LEGH', 'LEGN', 'LFMD', 'LFWD', 'LGVN', 'LI', 'LIEN', 'LINC', 'LKQ', 'LNSR', 'LNZA', 'LOCO', 'LODE', 'LOGC', 'LPRO', 'LQDA', 'LSTA', 'LUNR', 'LVLU', 'LX', 'LXRX', 'MDAI', 'MDGL', 'MDWD', 'MEI', 'MERC', 'MESO', 'MFIN', 'MG', 'MGIC', 'MGNX', 'MLCO', 'MNKD', 'MNST', 'MOLN', 'MRC', 'MRSN', 'MRX', 'MSC', 'MSGM', 'MU', 'MYGN', 'MYRG', 'NATR', 'NCLH', 'NCNO', 'NCSM', 'NDLS', 'NIO', 'NIU', 'NN', 'NNBR', 'NNOX', 'NOA', 'NPCE', 'NRXS', 'NSPR', 'NTLA', 'NVDA', 'NVGS', 'NVRI', 'NVTS', 'NYAX', 'OCGN', 'ODD', 'OLLI', 'OLPX', 'OPCH', 'OPK', 'OPRX', 'OPTN', 'OSS', 'OSUR', 'OXM', 'OXSQ', 'PCRX', 'PDD', 'PGNY', 'PHARM', 'PHAT', 'PLBY', 'PLUG', 'POCI', 'PONY', 'PPC', 'PRGS', 'PROF', 'PSTL', 'PTLO', 'PTMN', 'QRHC', 'QSG', 'RAIL', 'RC', 'RCMT', 'RDNT', 'REFI', 'RELY', 'RGTI', 'RIG', 'RLAY', 'RRC', 'RS', 'RUN', 'RUSHA', 'RVMD', 'RYTM', 'SAIC', 'SAMG', 'SBLK', 'SCOR', 'SCPH', 'SCS', 'SEAT', 'SEER', 'SENS', 'SERV', 'SFIX', 'SGA', 'SGHT', 'SGRY', 'SHEN', 'SHIM', 'SHIP', 'SHLS', 'SIGA', 'SII', 'SJW', 'SKIN', 'SKYE', 'SLDB', 'SLDP', 'SNCR', 'SNDX', 'SOBO', 'SON', 'SOWG', 'SPRY', 'SPT', 'SRAD', 'SSSS', 'SSTI', 'STG', 'STIM', 'STRO', 'STRR', 'STZ', 'SUNS', 'TAC', 'TARS', 'TBCH', 'TCMD', 'TELA', 'TEN', 'TEVA', 'TFII', 'TFX', 'TGB', 'TGTX', 'THRM', 'THTX', 'TIGO', 'TIGR', 'TISI', 'TITN', 'TK', 'TLS', 'TLX', 'TMCI', 'TOI', 'TVTX', 'TWFG', 'UCL', 'ULY', 'UNF', 'USEA', 'USEG', 'USIO', 'VATE', 'VCEL', 'VERO', 'VERV', 'VFF', 'VIOT', 'VRA', 'VRCA', 'VRNA', 'VYGR', 'WALD', 'WEST', 'WFCF', 'WFRD', 'WGO', 'WRD', 'WSR', 'WTI', 'WULF', 'WVE', 'WW', 'XFOR', 'XGN', 'XNET', 'YMAB', 'YY', 'ZIMV', 'ZSPC', 'ZUMZ', 'ZVRA', 'ZYME']

In [12]:
ticker = 'NVDA'
press_releases = fd.get_press_releases(ticker)
press_releases

NVDA is available

[{'ticker': 'NVDA',
  'title': 'NVIDIA Announces Financial Results for Fourth Quarter and Fiscal 2025',
  'url': 'https://www.globenewswire.com/news-release/2025/02/26/3033384/0/en/NVIDIA-Announces-Financial-Results-for-Fourth-Quarter-and-Fiscal-2025.html',
  'date': '2025-02-26T21:20:00Z',
  'text': 'SANTA CLARA, Calif., Feb. 26, 2025 (GLOBE NEWSWIRE) -- NVIDIA (NASDAQ: NVDA) today reported revenue for the fourth quarter ended January 26, 2025, of $39.3 billion, up 12% from the previous quarter and up 78% from a year ago.\n\nFor the quarter, GAAP earnings per diluted share was $0.89, up 14% from the previous quarter and up 82% from a year ago. Non-GAAP earnings per diluted share was $0.89, up 10% from the previous quarter and up 71% from a year ago.\n\nFor fiscal 2025, revenue was $130.5 billion, up 114% from a year ago. GAAP earnings per diluted share was $2.94, up 147% from a year ago. Non-GAAP earnings per diluted share was $2.99, up 130% from a year ago.\n\n“Demand for Blackwell is amazing as reasoning AI adds another scaling law — increasing compute for training makes models smarter and increasing compute for long thinking makes the answer smarter,” said Jensen Huang, founder and CEO of NVIDIA.\n\n“We’ve successfully ramped up the massive-scale production of Blackwell AI supercomputers, achieving billions of dollars in sales in its first quarter. AI is advancing at light speed as agentic AI and physical AI set the stage for the next wave of AI to revolutionize the largest industries.”\n\nNVIDIA will pay its next quarterly cash dividend of $0.01 per share on April 2, 2025, to all shareholders of record on March 12, 2025.\n\nQ4 Fiscal 2025 Summary\n\nFiscal 2025 Summary\n\n*All per share amounts presented herein have been retroactively adjusted to reflect the ten-for-one stock split, which was effective June 7, 2024.\n\nOutlookNVIDIA’s outlook for the first quarter of fiscal 2026 is as follows:\n\nHighlights\n\nNVIDIA achieved progress since its previous earnings announcement in these areas:\n\nData Center\n\nGaming and AI PC\n\nProfessional Visualization\n\nAutomotive and Robotics\n\nCFO CommentaryCommentary on the quarter by Colette Kress, NVIDIA’s executive vice president and chief financial officer, is available athttps://investor.nvidia.com.\n\nConference Call and Webcast InformationNVIDIA will conduct a conference call with analysts and investors to discuss its fourth quarter and fiscal 2025 financial results and current financial prospects today at 2 p.m. Pacific time (5 p.m. Eastern time). A live webcast (listen-only mode) of the conference call will be accessible at NVIDIA’s investor relations website,https://investor.nvidia.com. The webcast will be recorded and available for replay until NVIDIA’s conference call to discuss its financial results for its first quarter of fiscal 2026.\n\nNon-GAAP MeasuresTo supplement NVIDIA’s condensed consolidated financial statements presented in accordance with GAAP, the company uses non-GAAP measures of certain components of financial performance. These non-GAAP measures include non-GAAP gross profit, non-GAAP gross margin, non-GAAP operating expenses, non-GAAP operating income, non-GAAP other income (expense), net, non-GAAP net income, non-GAAP net income, or earnings, per diluted share, and free cash flow. For NVIDIA’s investors to be better able to compare its current results with those of previous periods, the company has shown a reconciliation of GAAP to non-GAAP financial measures. These reconciliations adjust the related GAAP financial measures to exclude stock-based compensation expense, acquisition-related and other costs, other, gains from non-marketable and publicly-held equity securities, net, interest expense related to amortization of debt discount, and the associated tax impact of these items where applicable. Free cash flow is calculated as GAAP net cash provided by operating activities less both purchases related to property and equipment and intangible assets and principal payments on property and equipment and intangible assets. NVIDIA believes the presentation of its non-GAAP financial measures enhances the user’s overall understanding of the company’s historical financial performance. The presentation of the company’s non-GAAP financial measures is not meant to be considered in isolation or as a substitute for the company’s financial results prepared in accordance with GAAP, and the company’s non-GAAP measures may be different from non-GAAP measures used by other companies.\n\nAbout NVIDIANVIDIA(NASDAQ: NVDA) is the world leader in accelerated computing.\n\nCertain statements in this press release including, but not limited to, statements as to: AI advancing at light speed as agentic AI and physical AI set the stage for the next wave of AI to revolutionize the largest industries; expectations with respect to growth, performance and benefits of NVIDIA’s products, services and technologies, including Blackwell, and related trends and drivers; expectations with respect to supply and demand for NVIDIA’s products, services and technologies, including Blackwell, and related matters including inventory, production and distribution; expectations with respect to NVIDIA’s third party arrangements, including with its collaborators and partners; expectations with respect to technology developments and related trends and drivers; future NVIDIA cash dividends or other returns to stockholders; NVIDIA’s financial and business outlook for the first quarter of fiscal 2026 and beyond; projected market growth and trends; expectations with respect to AI and related industries; and other statements that are not historical facts are risks and uncertainties that could cause results to be materially different than expectations. Important factors that could cause actual results to differ materially include: global economic and political conditions; NVIDIA’s reliance on third parties to manufacture, assemble, package and test NVIDIA’s products; the impact of technological development and competition; development of new products and technologies or enhancements to NVIDIA’s existing product and technologies; market acceptance of NVIDIA’s products or NVIDIA’s partners’ products; design, manufacturing or software defects; changes in consumer preferences or demands; changes in industry standards and interfaces; unexpected loss of performance of NVIDIA’s products or technologies when integrated into systems; and changes in applicable laws and regulations, as well as other factors detailed from time to time in the most recent reports NVIDIA files with the Securities and Exchange Commission, or SEC, including, but not limited to, its annual report on Form 10-K and quarterly reports on Form 10-Q. Copies of reports filed with the SEC are posted on the company’s website and are available from NVIDIA without charge. These forward-looking statements are not guarantees of future performance and speak only as of the date hereof, and, except as required by law, NVIDIA disclaims any obligation to update these forward-looking statements to reflect future events or circumstances.\n\n© 2025 NVIDIA Corporation. All rights reserved. NVIDIA, the NVIDIA logo, GeForce RTX, NVIDIA Cosmos, NVIDIA Spectrum-X, NVIDIA DGX, NVIDIA DRIVE, NVIDIA DRIVE AGX Orin, NVIDIA Grace, NVIDIA Jetson Orin Nano, NVIDIA NIM and NVIDIA Omniverse are trademarks and/or registered trademarks of NVIDIA Corporation in the U.S. and/or other countries. Other company and product names may be trademarks of the respective companies with which they are associated. Features, pricing, availability and specifications are subject to change without notice.\n\nA photo accompanying this announcement is available athttps://www.globenewswire.com/NewsRoom/AttachmentNg/aabe86db-ce89-4434-b83c-495082979801'}]

## Connect DB

In [13]:
db.create_table('valuation_metrics', valuation_metrics)

In [14]:
db.read_table('valuation_metrics')

   Ticker  Price/Book EV/EBITDA
0    AAPL   48.688595    23.575
1    MSFT    9.548044    20.293
2    GOOG    6.297611    14.791
3    AMZN   7.2248516    17.413
4    TSLA    10.54296     53.93
5    META     8.16247     17.29
6    NFLX    16.69038      37.8
7    NVDA   36.908363    33.409
8     AMD   3.0171587    32.024
9    NVDA   36.908363    33.409
10   TSLA    10.54296     53.93
11     BA         N/A   -18.439
12      V   17.812403    25.846
13   GOOG    6.297611    14.791
14    SPY         N/A       N/A
15   SPCE  0.44332957    -0.179
16   BABA   0.3310344    13.377
17   MSTR   4.1399164   -43.356
18    DIS   1.7925297    12.154
19   PYPL   3.4152036    11.218
20   SHOP   11.495295    91.456
21   COIN   4.7329516    19.443
22     SQ   2.6906772     42.31
23   INTC   1.0616766    19.484
24   CSCO   5.3703966    17.456
25    IBM    8.588874    26.133
26     GE   11.452759    24.819
27    AMD   3.0171587    32.024
28    WMT    7.639513    17.625
29      T   1.8466208     7.949

In [15]:
db.show_tables()

  Tables_in_Elite_Traders
0       valuation_metrics

In [16]:
db.drop_table('valuation_metrics')

In [17]:
db.show_tables()

Empty DataFrame
Columns: [Tables_in_Elite_Traders]
Index: []